### ISSUE TITLE
Getting NaNs

### ISSUE THREAD

**Issue by yungNeiko** [egrueebler/fca#9]
Hey first of all sorry for the big post but im unsure how to make it smaller and understandable. So I’m running into a problem where I’m only getting NaNs for the index. Here is my script with reprex (sorry I wasn’t able to getting it colored). But first maybe some previous knowledge about my dataset. I computed a matrix in QGIS to get the travel time from the community center point to the next hospital. In the whole analysis I have 2562 community center points and 96 hospitals so in total 245.952 rows in the whole matrix. Then I attached the population of the community’s and the number of beds form the hospital to the matrix and exported it as a .csv. Here a small preview:

FROM_ID	  TO_ID	DURATION_H	GN250_EWZ	MT_Supply
1	           1	           2.1920917	      95	          53
1	           2	           2.8308111	      95	          0
1	           3	           1.7108444	      95	          268
1	           4	           4.2568139	      95	          0
…	           …	           …	                      …	          …
2	           1	           2.4006611	     100	          53
2	           2	           3.0393778	     100	          0
2	           3	           2.4169056	     100	          268
2	           4	           3.0401194	     100	          0
…	           …	           …	                       …	          …

FROM_ID = community center point as IDs
TO_ID = hospitals as IDs
DURATION_H = travel time in hours
GN250_EWZ = population of the community’s
MT_Supply = number of beds

So now to my code: it starts with some data management, because I only wanted to use one file for the whole necessary information’s for the calculation. First, I load the csv file, then I create a subset for the population, then the same for the supply’s and then, with tidyverse, I rotated my travel time matrix so it looks like the time matrix D in your tutorial. Well and the rest is your package with my variable names.

exceldata = read.csv("MY_PATH\\MT_Matrix.csv")                                                                       
dfdaten = data.frame(exceldata)

dfpop = dfdaten[seq(1, nrow(dfdaten), 96), ]
pop <- dfpop [ , c("FROM_ID", "GN250_EWZ")]
pop
#>        FROM_ID GN250_EWZ
#> 1            1                95
#> 97           2               100
#> 193          3                87
#> 289          4               101
........................................
#> 245857    2562              2841

dfsup = dfdaten[1:96, ]
sup <- dfsup [ , c("TO_ID", "MT_Supply")]
sup
#>    TO_ID MT_Supply
#> 1      1                 0
#> 2      2                 0
#> 3      3                71
#> 4      4                 0
........................................
#> 96    96                10

wide_dfdaten <- dfdaten %>%
  select(FROM_ID, TO_ID, DURATION_H) %>%
  pivot_wider(
        names_from = FROM_ID,
        values_from = DURATION_H) 

wide_dfdaten <- select(wide_dfdaten, -TO_ID) 
dfmatrix <- as.matrix(wide_dfdaten)

D <- as.matrix(dfmatrix)
D
#>           1        2         3        4        5        6         7        8
#> 1  2.192092 2.400661 1.2985972 2.232211 2.277861 2.321839 1.8546333 2.711131
#> 2  2.830811 3.039378 1.9373167 2.870928 2.916581 2.960558 2.4933528 3.349850
#> 3  1.710844 2.416906 2.0031778 2.171542 1.992422 2.305869 1.0162639 1.171203
#> 4  4.256814 3.040119 3.6113389 2.939856 3.573914 4.386561 3.4875583 4.326528
........................................
#>         2556      2557      2558     2559     2560      2561      2562
#> 1  1.6090083 2.0773194 1.4695028 2.462303 2.841375 2.0571611 1.9706111
#> 2  2.2477278 2.7160389 2.1082222 3.101022 3.480092 2.6958806 2.6093306
#> 3  1.6252556 1.7918806 1.8390111 2.478550 2.555933 1.7717194 1.3002500
#> 4  3.0564833 3.6927194 3.3801472 2.841831 3.356775 3.6725583 3.5860111

W <- dist_normalize(
  D,
  d_max = 30,
  imp_function = "gaussian", function_d_max = 0.01
)

pop <- pop[order(pop$FROM_ID), ]
sup <- sup[order(sup$TO_ID), ]

(p <- setNames(pop$GN250_EWZ, as.character(pop$FROM_ID)))
#>     1     2     3     4     5     6     7     8     9    10    11    12    13 
#>    95   100    87   101   723   579  2220  1074    90   471   258   866   162 

(s <- setNames(sup$MT_Supply, as.character(sup$TO_ID)))
#>  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 
#>  0  0 71  0  0  0  0 75  0  0  0  0  0  0  0  0  0  0 70 40  7 17 56 48 36 20 

MT_mh3sfca <- spai_mh3sfca(p, s, W, step = 3)
MT_mh3sfca
#>      step3
#> 1      NaN
#> 2      NaN
#> 3      NaN
#> 4      NaN
........................................
#> 2562   NaN
reprex()

**Comment by egrueebler** [comment]
Hey, nice that you are using our package!
From the code bits you have posted, I have a three main recommendations:

- Make sure that you don't have any NAs in any of the used datasets (use for example: [matrix[is.na(matrix)] <- 0] to set NAs in the matrix to zero).
- Make sure that you have the suitable data types (check the documentation of the R package for the required data types: https://cran.r-project.org/web/packages/fca/fca.pdf / use for example the function class() to check the data types of your datasets).
- Check that the number of entries in your population and demand dataset meet the number of columns and rows in the matrix. Otherwise there might be something wrong with your datasets.

Hopefully you get there using these recommendations. Otherwise I recommend that you post a fully reproducible example, which only uses a small subset of the data.

**Comment by yungNeiko** [comment]
Hey, thanks for the reply!

So I checked my datasets and I have zero NAs. For the classes I got this back:

> class(p)
[1] "integer"
> class(s)
[1] "integer"
> class(W)
[1] "matrix" "array"

And the for the last bullet point I checked the numbers and they match. So from my understanding maybe I should redo my analysis in QGIS first and see if something changes. If nothing changes I'm posting you a comment with a fully reproducible example, which only uses a small subset of mydata. :)

**Comment by egrueebler** [comment]
Another suggestion: make sure, that your matrix has ncol population values and nrow supply values. Otherwise you need to rearrange your matrix (exchange cols and rows).

**Comment by yungNeiko** [comment]
Hey I'm back with the same results... sadly. 

I worte I would only give a small subset of my data but I'm not quite sure how to because of the formating in the comment section. So I uploaded my whole dataset. If it is not trustworthy to you please guide me how to give you a good subset of my data.

[MT_Matrix.csv](https://github.com/egrueebler/fca/files/10745419/MT_Matrix.csv)

**Comment by egrueebler** [comment]
I meant, that you should take a subset of all your data (e.g., 5 supplies, 3 population points and 15 matrix entries), so that you can post the complete code reproducibly here and show, where the NAs get from (check through step 1 to 3).
I read your initial post again and you were saying that you have 245'952 rows in the matrix. That must be wrong, as you should have nrows of your supply, which means 96 (the hospitals) in your case. So maybe check that again.

**Comment by yungNeiko** [comment]
Yes, you are right with the rows in the initial post but that was just a typo, sorry. I meant columns.

What’s odd now is that I tested my script with different data. Which I created the same way as the one where I have trouble with but this time it worked. The only difference in the data is that in the one which doesn’t work there are some supplies with a value of 0. And as I checked the steps one per time, as you mentioned, I got the first NaNs in step 2. Maybe that’s my problem?

But if needed I will try to post a subset of my data tomorrow in the comments.

**Comment by egrueebler** [comment]
I'm pretty sure that this is the problem. If you have supplies with a value of 0 those aren't actually supplies which can be considered (as they don't have any capacities and are therefore not supplies within reach). The second step in the MH3SFCA-method divides each supply-capacity through all the weighed population sizes within reach. So if you have zero values in step 1 you would divide the supply capacities through zero which is always NA. So check for zero values in your step 1 result and if there are zero values there, eliminate the supplies without capacities (from your supply dataset and your matrix - otherwise you will get trouble having different numbers of rows). Good luck!

**Comment by yungNeiko** [comment]
After I had no more zeros in my supply values everything worked!

Thanks for the help! :)

**Comment by egrueebler** [comment]
Perfect! I hope you'll get some interesting analyses by using the package. :)
